name: deploy-blog
on:
  push:
    branches:
      - master

jobs:
  build_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - run: cd ./site
      - run: echo $PWD
      - run: ls -la
      - run: python -m pip install -r requirements.txt
      - run: pelican content -o output -s publishconf.py

      - name: copy compiled site via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_KEY }}
          source: 'output/*'
          target: 'blog/output'
